name: Terraform Deployment

on:
  push:
    branches:
      - master

jobs:
  check_terraform_installed:
    runs-on: ubuntu-latest

    steps:
    - name: Check Terraform installation
      id: check_terraform
      run: |
        if command -v terraform &> /dev/null; then
          echo "::set-output name=installed::true"
        else
          echo "::set-output name=installed::false"
        fi

  terraform_deploy:
    needs: check_terraform_installed
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set Terraform variables
      run: |
        echo "aws_region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
        echo "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" >> $GITHUB_ENV

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      if: needs.check_terraform_installed.outputs.installed == 'false'
      with:
        terraform_version: ${{ secrets.TERRAFORM_VERSION }}

    - name: git clone
      run: git clone https://github.com/awslabs/data-on-eks.git

    - name: install.sh
      run: cd data-on-eks/analytics/terraform/datahub-on-eks
           chmod +x install.sh
           ./install.sh

    
